namespace SportsLibrary.Core
{
    /// <summary>
    /// Enumeration representing country codes for various countries.
    /// </summary>
    public enum CountryCode
    {
        Poland,
        Germany,
        France,
        Spain,
        Italy,
        UnitedKingdom,
        UnitedStates,
        Canada,
        Australia,
        Japan,
        China,
        Brazil,
        Russia,
        India,
        SouthAfrica,
        Mexico,
        Argentina,
        Netherlands,
        Belgium,
        Sweden,
        Norway,
        Denmark,
        Finland,
        Switzerland,
        Austria,
        Portugal,
        Greece,
        Turkey,
        SouthKorea,
        NorthKorea,
        SaudiArabia,
        UnitedArabEmirates,
        Egypt,
        Nigeria,
        Kenya,
        Morocco,
        Algeria,
        Tunisia,
        Ghana,
        IvoryCoast,
        Senegal,
        Cameroon,
        Uruguay,
        Paraguay,
        Chile,
        Colombia,
        Venezuela,
        Peru,
        Ecuador,
        Bolivia,
        Cuba,
        DominicanRepublic,
        Haiti,
        Jamaica,
        TrinidadAndTobago,
        Barbados,
        Bahamas,
        Panama,
        CostaRica,
        ElSalvador,
        Guatemala,
        Honduras,
        Nicaragua,
        Belize,
        Luxembourg,
        Liechtenstein,
        Monaco,
        Andorra,
        SanMarino,
        VaticanCity,
        Cyprus,
        Malta,
        Iceland,
        NewZealand,
        Singapore,
        Malaysia,
        Indonesia,
        Philippines,
        Vietnam,
        Thailand,
        Myanmar,
        Cambodia,
        Laos,
        Bangladesh,
        SriLanka,
        Nepal,
        Bhutan,
        Maldives,
        Afghanistan,
        Iran,
        Iraq,
        Syria,
        Lebanon,
        Jordan,
        Yemen,
        Oman,
        Qatar,
        Kuwait,
        Bahrain,
        CzechRepublic,
        Slovakia,
        Hungary,
        Romania,
        Bulgaria,
        Serbia,
        Croatia,
        BosniaAndHerzegovina,
        Slovenia,
        NorthMacedonia,
        Montenegro,
        Kosovo,
        Albania,
        Belarus,
        Ukraine,
        Moldova,
        Estonia,
        Latvia,
        Lithuania,
        Kazakhstan,
        Uzbekistan,
        Turkmenistan,
        Kyrgyzstan,
        Tajikistan,
        Armenia,
        Azerbaijan,
        Georgia,
    }

    public static class CountryCodeExtensions
    {
        public static string ToCountryCode(this CountryCode countryCode)
        {
            return countryCode switch
            {
                CountryCode.Poland => "POL",
                CountryCode.Germany => "GER",
                CountryCode.France => "FRA",
                CountryCode.Spain => "ESP",
                CountryCode.Italy => "ITA",
                CountryCode.UnitedKingdom => "GBR",
                CountryCode.UnitedStates => "USA",
                CountryCode.Canada => "CAN",
                CountryCode.Australia => "AUS",
                CountryCode.Japan => "JPN",
                CountryCode.China => "CHN",
                CountryCode.Brazil => "BRA",
                CountryCode.Russia => "RUS",
                CountryCode.India => "IND",
                CountryCode.SouthAfrica => "RSA",
                CountryCode.Mexico => "MEX",
                CountryCode.Argentina => "ARG",
                CountryCode.Netherlands => "NED",
                CountryCode.Belgium => "BEL",
                CountryCode.Sweden => "SWE",
                CountryCode.Norway => "NOR",
                CountryCode.Denmark => "DEN",
                CountryCode.Finland => "FIN",
                CountryCode.Switzerland => "SUI",
                CountryCode.Austria => "AUT",
                CountryCode.Portugal => "POR",
                CountryCode.Greece => "GRE",
                CountryCode.Turkey => "TUR",
                CountryCode.SouthKorea => "KOR",
                CountryCode.NorthKorea => "PRK",
                CountryCode.SaudiArabia => "KSA",
                CountryCode.UnitedArabEmirates => "UAE",
                CountryCode.Egypt => "EGY",
                CountryCode.Nigeria => "NGA",
                CountryCode.Kenya => "KEN",
                CountryCode.Morocco => "MAR",
                CountryCode.Algeria => "ALG",
                CountryCode.Tunisia => "TUN",
                CountryCode.Ghana => "GHA",
                CountryCode.IvoryCoast => "CIV",
                CountryCode.Senegal => "SEN",
                CountryCode.Cameroon => "CMR",
                CountryCode.Uruguay => "URU",
                CountryCode.Paraguay => "PAR",
                CountryCode.Chile => "CHI",
                CountryCode.Colombia => "COL",
                CountryCode.Venezuela => "VEN",
                CountryCode.Peru => "PER",
                CountryCode.Ecuador => "ECU",
                CountryCode.Bolivia => "BOL",
                CountryCode.Cuba => "CUB",
                CountryCode.DominicanRepublic => "DOM",
                CountryCode.Haiti => "HAI",
                CountryCode.Jamaica => "JAM",
                CountryCode.TrinidadAndTobago => "TTO",
                CountryCode.Barbados => "BAR",
                CountryCode.Bahamas => "BAH",
                CountryCode.Panama => "PAN",
                CountryCode.CostaRica => "CRC",
                CountryCode.ElSalvador => "ESA",
                CountryCode.Guatemala => "GUA",
                CountryCode.Honduras => "HON",
                CountryCode.Nicaragua => "NCA",
                CountryCode.Belize => "BIZ",
                CountryCode.Luxembourg => "LUX",
                CountryCode.Liechtenstein => "LIE",
                CountryCode.Monaco => "MON",
                CountryCode.Andorra => "AND",
                CountryCode.SanMarino => "SMR",
                CountryCode.VaticanCity => "VAT",
                CountryCode.Cyprus => "CYP",
                CountryCode.Malta => "MLT",
                CountryCode.Iceland => "ISL",
                CountryCode.NewZealand => "NZL",
                CountryCode.Singapore => "SGP",
                CountryCode.Malaysia => "MAS",
                CountryCode.Indonesia => "INA",
                CountryCode.Philippines => "PHI",
                CountryCode.Vietnam => "VIE",
                CountryCode.Thailand => "THA",
                CountryCode.Myanmar => "MYA",
                CountryCode.Cambodia => "CAM",
                CountryCode.Laos => "LAO",
                CountryCode.Bangladesh => "BAN",
                CountryCode.SriLanka => "SRI",
                CountryCode.Nepal => "NEP",
                CountryCode.Bhutan => "BHU",
                CountryCode.Maldives => "MDV",
                CountryCode.Afghanistan => "AFG",
                CountryCode.Iran => "IRI",
                CountryCode.Iraq => "IRQ",
                CountryCode.Syria => "SYR",
                CountryCode.Lebanon => "LIB",
                CountryCode.Jordan => "JOR",
                CountryCode.Yemen => "YEM",
                CountryCode.Oman => "OMA",
                CountryCode.Qatar => "QAT",
                CountryCode.Kuwait => "KUW",
                CountryCode.Bahrain => "BRN",
                CountryCode.CzechRepublic => "CZE",
                CountryCode.Slovakia => "SVK",
                CountryCode.Hungary => "HUN",
                CountryCode.Romania => "ROU",
                CountryCode.Bulgaria => "BUL",
                CountryCode.Serbia => "SRB",
                CountryCode.Croatia => "CRO",
                CountryCode.BosniaAndHerzegovina => "BIH",
                CountryCode.Slovenia => "SLO",
                CountryCode.NorthMacedonia => "MKD",
                CountryCode.Montenegro => "MNE",
                CountryCode.Kosovo => "KOS",
                CountryCode.Albania => "ALB",
                CountryCode.Belarus => "BLR",
                CountryCode.Ukraine => "UKR",
                CountryCode.Moldova => "MDA",
                CountryCode.Estonia => "EST",
                CountryCode.Latvia => "LAT",
                CountryCode.Lithuania => "LTU",
                CountryCode.Kazakhstan => "KAZ",
                CountryCode.Uzbekistan => "UZB",
                CountryCode.Turkmenistan => "TUK",
                CountryCode.Kyrgyzstan => "KGZ",
                CountryCode.Tajikistan => "TJK",
                CountryCode.Armenia => "ARM",
                CountryCode.Azerbaijan => "AZE",
                CountryCode.Georgia => "GEO",
                _ => throw new ArgumentOutOfRangeException(nameof(countryCode), $"Not expected country code value: {countryCode}"),
            };
        }
    }
}